[package]
name = "example_lib"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
mondrian = { path = "../../" }
pollster = "0.4.0"
raw-window-handle = "0.6.0"
wgpu = "27.0.1"
winit = "0.30.12"
